utils.c: Fix dirname() handling in run_ptests()
It is required to use the return value of dirname() instead of
assuming that dirname() modifies the input string. While certain
implementations of dirname(), for example glibc, *may* modify the
input string, this is not guaranteed behavior. CHERI Musl, on the
other hand, does not modify the input string but instead returns a
pointer to a statically allocated string [1].

Previously, ptest-runner would fail on musl systems specific
implementation [1]:

```
$ ptest-runner busybox
START: ptest-runner
2026-02-27T09:21
BEGIN: /usr/lib/busybox/ptest/run-ptest
ERROR: Unable to chdir(/usr/lib/busybox/ptest/run-ptest), Not a directory

ERROR: Exited from signal Killed (9)
DURATION: 0
END: /usr/lib/busybox/ptest/run-ptest
2026-02-27T09:21
STOP: ptest-runner
TOTAL: 1 FAIL: 1
```

[1]:
https://git.morello-project.org/morello/musl-libc/-/blob/e379080e966573c79096f80d89e5b42f469ac8d1/src/misc/dirname.c

Signed-off-by: Florian Schmaus <florian.schmaus@codasip.com>
Signed-off-by: Anibal Limon <anibal@limonsoftware.com>